version: '3.8'

services:
  backend:
    image: maven
    volumes:
      - "./:/app"
      # Mounting user's local .m2-directory,
      # for custom settings.xml and for caching dependencies.
      - "~/.m2:/root/.m2"
    ports:
      - 5005:5005 # Debug port
      - 8080:8080 # Backend HTTP server port
    working_dir: /app
    command: "mvn quarkus:dev -Dquarkus.http.host=0.0.0.0"
